# Generated by Django 6.0.3 on 2026-04-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook_id', models.CharField(max_length=100)),
                ('usuario_nome', models.CharField(default='Anônimo', max_length=100)),
                ('texto', models.TextField()),
                ('estrelas', models.IntegerField(default=5)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
